steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-api-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-api-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'spring-api-service', '--image', 'gcr.io/$PROJECT_ID/spring-api-service', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
